name: gridmapenv
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy
  - scipy
  - pandas
  - requests 
  - joblib
  - fiona
  - geos
  - shapely
  - pyproj
  - geopandas
  - geojson
  - rtree
  - psycopg2
  - geopy
  - gdal
  - matplotlib
  - descartes
  - branca
  - tobler
  - folium
  - ipyleaflet
  - jupyter_contrib_nbextensions
  - pip:
    - -r file:requirements.txt

